//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GummyBearsGame.GameService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Map", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Models")]
    [System.SerializableAttribute()]
    public partial class Map : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.Field[] FieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal JuiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal JuiceAIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MoneyAIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.Field[] Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Juice {
            get {
                return this.JuiceField;
            }
            set {
                if ((this.JuiceField.Equals(value) != true)) {
                    this.JuiceField = value;
                    this.RaisePropertyChanged("Juice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal JuiceAI {
            get {
                return this.JuiceAIField;
            }
            set {
                if ((this.JuiceAIField.Equals(value) != true)) {
                    this.JuiceAIField = value;
                    this.RaisePropertyChanged("JuiceAI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MoneyAI {
            get {
                return this.MoneyAIField;
            }
            set {
                if ((this.MoneyAIField.Equals(value) != true)) {
                    this.MoneyAIField = value;
                    this.RaisePropertyChanged("MoneyAI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Field", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Models")]
    [System.SerializableAttribute()]
    public partial class Field : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DefenceMultiplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GoldMultiplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GummiesMultiplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GummiesNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.GummyType GummiesTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal JuiceMultiplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.FieldOwner OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DefenceMultiplier {
            get {
                return this.DefenceMultiplierField;
            }
            set {
                if ((this.DefenceMultiplierField.Equals(value) != true)) {
                    this.DefenceMultiplierField = value;
                    this.RaisePropertyChanged("DefenceMultiplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GoldMultiplier {
            get {
                return this.GoldMultiplierField;
            }
            set {
                if ((this.GoldMultiplierField.Equals(value) != true)) {
                    this.GoldMultiplierField = value;
                    this.RaisePropertyChanged("GoldMultiplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GummiesMultiplier {
            get {
                return this.GummiesMultiplierField;
            }
            set {
                if ((this.GummiesMultiplierField.Equals(value) != true)) {
                    this.GummiesMultiplierField = value;
                    this.RaisePropertyChanged("GummiesMultiplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GummiesNumber {
            get {
                return this.GummiesNumberField;
            }
            set {
                if ((this.GummiesNumberField.Equals(value) != true)) {
                    this.GummiesNumberField = value;
                    this.RaisePropertyChanged("GummiesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.GummyType GummiesType {
            get {
                return this.GummiesTypeField;
            }
            set {
                if ((this.GummiesTypeField.Equals(value) != true)) {
                    this.GummiesTypeField = value;
                    this.RaisePropertyChanged("GummiesType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal JuiceMultiplier {
            get {
                return this.JuiceMultiplierField;
            }
            set {
                if ((this.JuiceMultiplierField.Equals(value) != true)) {
                    this.JuiceMultiplierField = value;
                    this.RaisePropertyChanged("JuiceMultiplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.FieldOwner Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((this.OwnerField.Equals(value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GummyType", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Enums")]
    public enum GummyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Basic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warrior = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Magical = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldOwner", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Enums")]
    public enum FieldOwner : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoOne = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Player = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AI = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Models")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.Map MapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.GameAction[] OpponentMovesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.GameAction[] PlayerMovesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinished {
            get {
                return this.IsFinishedField;
            }
            set {
                if ((this.IsFinishedField.Equals(value) != true)) {
                    this.IsFinishedField = value;
                    this.RaisePropertyChanged("IsFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.Map Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MapId {
            get {
                return this.MapIdField;
            }
            set {
                if ((this.MapIdField.Equals(value) != true)) {
                    this.MapIdField = value;
                    this.RaisePropertyChanged("MapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.GameAction[] OpponentMoves {
            get {
                return this.OpponentMovesField;
            }
            set {
                if ((object.ReferenceEquals(this.OpponentMovesField, value) != true)) {
                    this.OpponentMovesField = value;
                    this.RaisePropertyChanged("OpponentMoves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.GameAction[] PlayerMoves {
            get {
                return this.PlayerMovesField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerMovesField, value) != true)) {
                    this.PlayerMovesField = value;
                    this.RaisePropertyChanged("PlayerMoves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.Game[] GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.Game[] Games {
            get {
                return this.GamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesField, value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameAction", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Models")]
    [System.SerializableAttribute()]
    public partial class GameAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GummyBearsGame.GameService.ActionType ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Field1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Field2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GummyBearsGame.GameService.ActionType Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Field1 {
            get {
                return this.Field1Field;
            }
            set {
                if ((this.Field1Field.Equals(value) != true)) {
                    this.Field1Field = value;
                    this.RaisePropertyChanged("Field1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Field2 {
            get {
                return this.Field2Field;
            }
            set {
                if ((this.Field2Field.Equals(value) != true)) {
                    this.Field2Field = value;
                    this.RaisePropertyChanged("Field2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionType", Namespace="http://schemas.datacontract.org/2004/07/GummyBears.Common.Enums")]
    public enum ActionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Void = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Move = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attack = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoveWithJuice = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sacrifice = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uprate = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surrend = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoLogin", ReplyAction="http://tempuri.org/IService/DoLoginResponse")]
        string DoLogin(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoLogin", ReplyAction="http://tempuri.org/IService/DoLoginResponse")]
        System.Threading.Tasks.Task<string> DoLoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaps", ReplyAction="http://tempuri.org/IService/GetMapsResponse")]
        GummyBearsGame.GameService.Map[] GetMaps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaps", ReplyAction="http://tempuri.org/IService/GetMapsResponse")]
        System.Threading.Tasks.Task<GummyBearsGame.GameService.Map[]> GetMapsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartGame", ReplyAction="http://tempuri.org/IService/StartGameResponse")]
        GummyBearsGame.GameService.Game StartGame(string sessionHandle, int mapId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/StartGame", ReplyAction="http://tempuri.org/IService/StartGameResponse")]
        System.Threading.Tasks.Task<GummyBearsGame.GameService.Game> StartGameAsync(string sessionHandle, int mapId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MakeMove", ReplyAction="http://tempuri.org/IService/MakeMoveResponse")]
        GummyBearsGame.GameService.Game MakeMove(string sessionHandle, GummyBearsGame.GameService.GameAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/MakeMove", ReplyAction="http://tempuri.org/IService/MakeMoveResponse")]
        System.Threading.Tasks.Task<GummyBearsGame.GameService.Game> MakeMoveAsync(string sessionHandle, GummyBearsGame.GameService.GameAction action);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : GummyBearsGame.GameService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<GummyBearsGame.GameService.IService>, GummyBearsGame.GameService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoLogin(string login, string password) {
            return base.Channel.DoLogin(login, password);
        }
        
        public System.Threading.Tasks.Task<string> DoLoginAsync(string login, string password) {
            return base.Channel.DoLoginAsync(login, password);
        }
        
        public GummyBearsGame.GameService.Map[] GetMaps() {
            return base.Channel.GetMaps();
        }
        
        public System.Threading.Tasks.Task<GummyBearsGame.GameService.Map[]> GetMapsAsync() {
            return base.Channel.GetMapsAsync();
        }
        
        public GummyBearsGame.GameService.Game StartGame(string sessionHandle, int mapId) {
            return base.Channel.StartGame(sessionHandle, mapId);
        }
        
        public System.Threading.Tasks.Task<GummyBearsGame.GameService.Game> StartGameAsync(string sessionHandle, int mapId) {
            return base.Channel.StartGameAsync(sessionHandle, mapId);
        }
        
        public GummyBearsGame.GameService.Game MakeMove(string sessionHandle, GummyBearsGame.GameService.GameAction action) {
            return base.Channel.MakeMove(sessionHandle, action);
        }
        
        public System.Threading.Tasks.Task<GummyBearsGame.GameService.Game> MakeMoveAsync(string sessionHandle, GummyBearsGame.GameService.GameAction action) {
            return base.Channel.MakeMoveAsync(sessionHandle, action);
        }
    }
}
